"""empty message

Revision ID: efb399a0d7a3
Revises: 0ceeeb5bfd31
Create Date: 2023-05-02 19:58:42.037686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb399a0d7a3'
down_revision = '0ceeeb5bfd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nascimento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('senha', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('senha')
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('nascimento')

    # ### end Alembic commands ###
